export const database = [
  {
    id: 1,
    name: 'Dr Sérgio Henrique de Paula tasso',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: true,
  },
  {
    id: 1,
    name: 'Dr Aldo fantini netto',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: true,
  },
  {
    id: 1,
    name: 'Francisco Cesar furtado',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: false,
  },
  {
    id: 1,
    name: 'Dr Aparecido dos Santos Rigo',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: false,
  },
  {
    id: 1,
    name: 'Dr Joaquim Marinheiro neto',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: false,
  },
  {
    id: 1,
    name: 'Dr Hersz Lichtcajer',
    telephone: '(16)37222541',
    whatsapp: '',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'Dermatologia',
    localPay: false,
  },
];
