export const database = [
  {
    id: 1,
    doctor: 'Dr Sérgio Henrique de Paula tasso',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'nefrologia',
    localPay: true,
    comment: 'bla bla',
  },
  {
    id: 2,
    doctor: 'Dr Aldo fantini netto',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'dermatologia',
    localPay: true,
    comment: 'bla bla',
  },
  {
    id: 3,
    doctor: 'Francisco Cesar furtado',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'urologia',
    localPay: false,
    comment: 'bla bla',
  },
  {
    id: 4,
    doctor: 'Dr Aparecido dos Santos Rigo',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'dermatologia',
    localPay: false,
    comment: 'bla bla',
  },
  {
    id: 5,
    doctor: 'Dr Joaquim Marinheiro neto',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'cardioloogia',
    localPay: false,
    comment: 'bla bla',
  },
  {
    id: 6,
    doctor: 'Dr Hersz Lichtcajer',
    telephone: '(16)37222541',
    whatsapp: '',
    number: '250',
    address: 'Rua joaquim spereta, 1250, São joaquim',
    specialty: 'dermatologia',
    localPay: false,
    comment: 'bla bla',
  },
];
